# Generated by Django 2.2 on 2019-06-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sittin_log_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_photo_url',
            field=models.CharField(max_length=1000),
        ),
    ]
